galaxy_info:
  author: Companies House
  description: Installs and configures a standardised base ClamAV configuration
  company: Companies House
  license: MIT
  min_ansible_version: "2.9"
  galaxy_tags:
    - antivirus
    - clamav
    - clamd
    - freshclam
