---
- name: Clean up old temp scan directories
  ansible.builtin.shell: |
    find {{ security_scans_base_dir }} -name "security-scan-*" -type d -mmin +360 -exec rm -rf {} \; 2>/dev/null || true
  become: true
  changed_when: false

- name: Compress old scan files
  ansible.builtin.shell: |
    # Compress files in existing scan directories
    find {{ security_scans_base_dir }} -maxdepth 2 -name "*.xml" -not -name "*.gz" -exec gzip {} \; 2>/dev/null || true
    find {{ security_scans_base_dir }} -maxdepth 2 -name "*.html" -not -name "*.gz" -exec gzip {} \; 2>/dev/null || true
    find {{ security_scans_base_dir }} -maxdepth 2 -name "*.report" -not -name "*.gz" -exec gzip {} \; 2>/dev/null || true
  when:
    - security_scans_retention_enabled | bool
    - security_scans_compress_files | bool
  changed_when: false
  become: true

- name: Clean old scan directories inline with retention policy
  ansible.builtin.shell: |
    set -o pipefail
    # Clean old scan directories before creating new one
    cd {{ security_scans_base_dir }}
    ls -dt */ 2>/dev/null | tail -n +{{ security_scans_retention_count }} | xargs rm -rf 2>/dev/null || true
  when: security_scans_retention_enabled | bool
  changed_when: false
  become: true
  args:
    executable: /bin/bash
