---
- name: Install packages and create directories
  ansible.builtin.include_tasks: 01_setup.yml

- name: Validate system requirements and datastreams
  ansible.builtin.include_tasks: 02_validation.yml

- name: Clean up old scans and manage retention
  ansible.builtin.include_tasks: 03_cleanup.yml

- name: Initialise scan workspace directory
  ansible.builtin.include_tasks: 04_initialise.yml

- name: Execute Lynis security audit
  ansible.builtin.include_tasks: 05_lynis.yml

- name: Execute OpenSCAP security scan
  ansible.builtin.include_tasks: 06_openscap.yml

- name: Validate completeness and store scan results
  ansible.builtin.include_tasks: 07_validate_and_store.yml

- name: Display security scan results and scores
  ansible.builtin.include_tasks: 08_display_results.yml
